-- Lumi — lote 3: 30 devocionais novos, REVISADOS E APROVADOS (publicados ao rodar este arquivo).
--
-- Rode uma vez no SQL Editor do Supabase. Se você já tinha rodado a versão em rascunho, o final
-- deste arquivo publica o que ficou pendente. Versão legível: docs/devocionais-rascunho.md.
--
-- Critérios (briefing §4, §8.3, §10, §11.2):
--   1. Sem culpa, vergonha ou pressão espiritual; o tom convida, não cobra.
--   2. Nenhum texto fala como se fosse Deus nem afirma o que Deus quer para a pessoa; onde há
--      interpretação, aparece como "uma leitura possível".
--   3. O versículo NÃO é citado nos textos: ele vem da NVI (YouVersion, id 129) no passo
--      "Versículo". Os textos só descrevem o que a passagem diz, sem aspas.
--   4. Temas que podem pesar (Salmos 34:18, Efésios 4:32) trazem a sugestão de conversar com
--      alguém de confiança.
--   5. O desafio de cada dia é uma ação pequena e concreta, ligada à constância (§7.1).
--
-- Seguro de rodar mais de uma vez: só insere o que ainda não existe (compara o título).

insert into public.content
  (title, body, passage_reference, youversion_version_id, application_text, challenge_text, prayer_text, published_at)
select v.title, v.body, v.passage_reference, 129, v.application_text, v.challenge_text, v.prayer_text, now()
from (values
  ($d$Descansar também é seguir o pastor$d$,
   $d$O salmo começa com a imagem de um pastor que leva as ovelhas a pastos verdes e águas tranquilas. A primeira coisa que aparece é descanso, não tarefa. Uma leitura possível é que ser cuidado vem antes de produzir. Se o seu dia foi corrido, esse momento pode ser só isso: parar um pouco, sem precisar provar nada a ninguém.$d$,
   'PSA.23.1-3',
   $d$Pense em um ponto do seu dia em que você corre por hábito, não por necessidade.$d$,
   $d$Antes da próxima tarefa, pare por 2 minutos, sem celular, só respirando.$d$,
   $d$Senhor, obrigado por cuidar de mim mesmo quando eu esqueço de parar. Me ajuda a descansar sem culpa e a seguir o dia com o coração mais leve.$d$),
  ($d$Nem tudo precisa estar entendido$d$,
   $d$O provérbio convida a confiar de todo o coração e a não se apoiar só no próprio entendimento. Não é um convite a desligar a cabeça: é um lembrete de que há decisões em que a gente não enxerga o caminho inteiro. Dá para dar o próximo passo mesmo sem ver o final.$d$,
   'PRO.3.5-6',
   $d$Qual decisão está parada esperando uma certeza total? Talvez um passo pequeno já baste por hoje.$d$,
   $d$Escolha uma decisão pendente e dê hoje o menor passo possível nela.$d$,
   $d$Pai, nem sempre eu entendo o caminho. Me ajuda a confiar e a dar o próximo passo com calma, sem esperar ter todas as respostas.$d$),
  ($d$Forças que voltam$d$,
   $d$O texto fala de quem espera e tem as forças renovadas. O versículo anterior reconhece que até os mais fortes se cansam, então o cansaço não é tratado como falha. Esperar, aqui, não é ficar parado sem fazer nada: é seguir caminhando sem a pressa de resolver tudo sozinho.$d$,
   'ISA.40.31',
   $d$Onde você tem se cobrado como se não pudesse se cansar?$d$,
   $d$Hoje, faça uma pausa curta de verdade em algum momento em que você normalmente seguiria direto.$d$,
   $d$Senhor, estou cansado de algumas coisas e não vou fingir o contrário. Renova minhas forças aos poucos, no meu ritmo e no teu tempo.$d$),
  ($d$Coragem não é ausência de medo$d$,
   $d$A ordem de ser forte e corajoso, dita a Josué em um momento de grande mudança, vem junto de uma promessa de companhia: o Senhor estaria com ele por onde fosse. A coragem do texto não nasce de não sentir medo, mas de não estar sozinho para enfrentá-lo.$d$,
   'JOS.1.9',
   $d$Existe algo que você vem adiando por medo? Dar o primeiro passo não exige ter perdido o medo.$d$,
   $d$Faça hoje uma coisa pequena que você vinha evitando.$d$,
   $d$Pai, tenho medo de algumas coisas que me esperam. Me lembra de que não caminho sozinho e me dá coragem para o próximo passo.$d$),
  ($d$Um convite para quem está cansado$d$,
   $d$Jesus convida os cansados e sobrecarregados a irem até ele e fala em descanso, em um jugo leve e em aprender com quem é manso e humilde de coração. É um convite, não uma cobrança. Se você chegou aqui cansado, já está no lugar de quem foi chamado.$d$,
   'MAT.11.28-30',
   $d$O que está pesando mais em você esta semana? Nomear o peso já é um primeiro passo.$d$,
   $d$Escreva em uma frase o que está te cansando e leia em voz baixa, como quem entrega.$d$,
   $d$Senhor, chego cansado e sem muita coisa para oferecer. Obrigado por me receber assim mesmo. Me ensina a descansar em ti.$d$),
  ($d$De onde vem o socorro$d$,
   $d$O salmista levanta os olhos para os montes e pergunta de onde virá o seu socorro. Perguntar é honesto: o texto não finge que não precisa de ajuda. A resposta vem logo em seguida, apontando para o Senhor, que fez o céu e a terra. Reconhecer que precisamos de socorro também faz parte da caminhada.$d$,
   'PSA.121.1-2',
   $d$Em que ponto você está tentando dar conta de tudo sozinho?$d$,
   $d$Peça ajuda a alguém hoje em algo pequeno, ou aceite uma ajuda que já foi oferecida.$d$,
   $d$Pai, levanto os olhos hoje procurando ajuda. Me ensina a pedir quando eu precisar e a confiar que não estou sozinho.$d$),
  ($d$Permanecer$d$,
   $d$Jesus usa a imagem da videira e dos ramos: quem permanece nele dá muito fruto, e sem ele os ramos nada podem fazer. A palavra-chave é permanecer: voltar, ficar, continuar. O que sustenta um ramo não é um esforço de um dia, mas estar ligado todos os dias.$d$,
   'JHN.15.5',
   $d$O que ajuda você a voltar para este momento todo dia, mesmo nos dias corridos?$d$,
   $d$Escolha um horário para o seu momento de amanhã e coloque no calendário.$d$,
   $d$Senhor, quero permanecer perto de ti nos dias bons e nos dias corridos. Me ajuda a voltar sempre, mesmo quando o dia não ajuda.$d$),
  ($d$Mente que se renova aos poucos$d$,
   $d$Paulo fala de não se conformar com o padrão deste mundo e de ser transformado pela renovação da mente. Renovar é um verbo de processo: acontece aos poucos, não de uma vez. Pequenas escolhas repetidas costumam pesar mais do que grandes resoluções.$d$,
   'ROM.12.2',
   $d$Existe um pensamento que se repete na sua cabeça e que você gostaria de responder de outro jeito?$d$,
   $d$Perceba um pensamento que volta hoje e escreva uma frase verdadeira e gentil para responder a ele.$d$,
   $d$Pai, quero pensar com mais clareza e menos peso. Vai renovando minha mente aos poucos, e me dá paciência com o processo.$d$),
  ($d$Sem se cansar de fazer o bem$d$,
   $d$Paulo incentiva a não desanimar de fazer o bem, porque haverá colheita no tempo certo, se não desistirmos. O texto reconhece que dá vontade de parar e fala em tempo certo: nem tudo dá resultado imediato. Gestos pequenos e repetidos vão formando algo que o dia a dia não deixa ver.$d$,
   'GAL.6.9',
   $d$Que bem pequeno você tem feito sem ver resultado ainda?$d$,
   $d$Faça hoje um gesto de bondade discreto: uma mensagem, uma ajuda, um agradecimento.$d$,
   $d$Senhor, às vezes me canso de fazer o bem sem ver retorno. Me ajuda a continuar com calma e a confiar no tempo certo.$d$),
  ($d$Tem tempo para tudo$d$,
   $d$Eclesiastes afirma que há tempo certo para cada propósito debaixo do céu. Para quem vive correndo, é um alívio: nem tudo é para agora e nem tudo cabe em um dia. Reconhecer a estação em que você está ajuda a não cobrar de si o que não pertence a esta estação.$d$,
   'ECC.3.1',
   $d$Em que estação você está agora: plantar, esperar, descansar, recomeçar?$d$,
   $d$Risque da lista de hoje uma coisa que pode ficar para outro tempo.$d$,
   $d$Pai, ensina-me a reconhecer o tempo em que estou. Me livra da pressa de viver tudo ao mesmo tempo.$d$),
  ($d$Vestir-se de gentileza$d$,
   $d$Paulo fala de revestir-se de compaixão, bondade, humildade, mansidão e paciência, suportando uns aos outros e perdoando, e acima de tudo de amor. Roupa a gente escolhe de manhã: dá para decidir qual atitude vestir antes de sair, mesmo nos dias em que ela não vem sozinha.$d$,
   'COL.3.12-14',
   $d$Com quem você vai conviver hoje que pede um pouco mais de paciência?$d$,
   $d$Escolha uma atitude da lista e pratique em uma conversa de hoje.$d$,
   $d$Senhor, me ajuda a vestir compaixão e paciência hoje, principalmente com quem me cansa. Que o amor seja a primeira peça.$d$),
  ($d$Ouvir primeiro$d$,
   $d$Tiago aconselha a ser pronto para ouvir, tardio para falar e tardio para se irar. São três pausas curtas que mudam o rumo de uma conversa. Ouvir de verdade é um tipo de cuidado: diz à outra pessoa que ela importa antes mesmo de ser respondida.$d$,
   'JAS.1.19',
   $d$Em que conversas você costuma responder antes de a outra pessoa terminar?$d$,
   $d$Em uma conversa de hoje, escute até o fim antes de responder.$d$,
   $d$Pai, me ensina a ouvir com atenção e a falar com cuidado. Que eu não tenha pressa em responder nem em me defender.$d$),
  ($d$Formado com cuidado$d$,
   $d$O salmista fala de ter sido formado no ventre e louva por ser feito de modo extraordinário. Em dias de comparação, o texto lembra de um valor que vem antes de qualquer conquista, aparência ou produtividade. Uma leitura possível é que você não precisa merecer o seu lugar: ele vem antes.$d$,
   'PSA.139.13-14',
   $d$Em que situações você se compara e sai se sentindo menos?$d$,
   $d$Escreva uma coisa em você pela qual é grato, sem relativizar.$d$,
   $d$Senhor, obrigado por me conheceres por inteiro. Me ajuda a me ver com mais gentileza e a parar de me medir pelos outros.$d$),
  ($d$Gratidão em pequenas doses$d$,
   $d$Paulo fala de estar alegre, orar sem cessar e dar graças em todas as circunstâncias. Repare na preposição: em todas as circunstâncias, não por todas elas. Uma leitura possível é que o texto não pede fingir que está tudo bem, mas procurar algo pelo que agradecer mesmo no meio do que não está.$d$,
   '1TH.5.16-18',
   $d$O que de bom, mesmo pequeno, aconteceu hoje?$d$,
   $d$Agradeça em voz alta por três coisas simples do seu dia.$d$,
   $d$Pai, mesmo nos dias difíceis eu quero reconhecer o que é bom. Abre meus olhos para as pequenas coisas pelas quais agradecer.$d$),
  ($d$Presença antes de tarefas$d$,
   $d$Marta recebe Jesus em casa e se ocupa com muitos afazeres; Maria se senta para ouvi-lo. Jesus diz a Marta que ela está agitada com muitas coisas e que Maria escolheu a boa parte. Não é um texto contra servir, e nem sobre quem é melhor: é sobre não deixar as tarefas ocuparem o lugar da presença.$d$,
   'LUK.10.38-42',
   $d$Em que momentos as tarefas do dia ocupam o lugar das pessoas, ou do descanso?$d$,
   $d$Faça hoje uma refeição ou conversa sem olhar o celular.$d$,
   $d$Senhor, tenho muitas coisas para fazer e me perco nelas. Me ajuda a estar inteiro no que importa.$d$),
  ($d$Luz sem holofote$d$,
   $d$Jesus diz aos seus ouvintes que eles são a luz do mundo e que ninguém acende uma lâmpada para escondê-la, mas para iluminar a casa. A imagem é simples e útil, sem espetáculo: a luz serve a quem está por perto. Boas ações feitas com simplicidade já cumprem esse papel.$d$,
   'MAT.5.14-16',
   $d$Quem está perto de você e poderia se beneficiar de uma pequena ajuda hoje?$d$,
   $d$Faça algo útil por alguém sem contar para ninguém.$d$,
   $d$Pai, quero ser uma luz simples e útil para quem está perto de mim. Me ajuda a servir sem precisar de aplauso.$d$),
  ($d$O céu também fala$d$,
   $d$O salmo diz que os céus declaram a glória de Deus e que o firmamento anuncia a obra de suas mãos, dia após dia, noite após noite. Uma leitura possível é que a criação é uma linguagem sem palavras: nem tudo precisa de explicação para ser sentido. Olhar para cima também pode ser uma forma de oração.$d$,
   'PSA.19.1-2',
   $d$Quando foi a última vez que você parou para olhar o céu?$d$,
   $d$Olhe para o céu por 1 minuto hoje, sem fazer mais nada.$d$,
   $d$Senhor, obrigado pela criação que fala sem palavras. Me ajuda a parar de vez em quando e perceber.$d$),
  ($d$Resposta que desarma$d$,
   $d$O provérbio diz que a resposta branda desvia a ira, enquanto a palavra ríspida provoca mais. Em conversas tensas, o tom decide muita coisa, às vezes mais do que o argumento. Responder com suavidade não é ceder: é escolher não alimentar o fogo.$d$,
   'PRO.15.1',
   $d$Qual conversa ou mensagem recente teria sido diferente com um tom mais calmo?$d$,
   $d$Em uma situação tensa de hoje, respire antes de responder e escolha um tom mais suave.$d$,
   $d$Pai, me ajuda a responder com calma quando eu estiver irritado. Que minhas palavras ajudem a apagar o fogo, não a acendê-lo.$d$),
  ($d$Perdoar também é processo$d$,
   $d$Paulo pede bondade e compaixão uns com os outros e perdão, como Deus perdoou em Cristo. Perdoar nem sempre acontece de uma vez, e não exige fingir que não doeu. Pode começar com algo pequeno: não alimentar o rancor hoje. Se a situação envolve algo grave, conversar com alguém de confiança também é uma forma de cuidado.$d$,
   'EPH.4.32',
   $d$Existe alguém ou algo que você carrega há muito tempo e gostaria de soltar aos poucos?$d$,
   $d$Escolha uma pequena atitude de hoje que não alimente um ressentimento antigo.$d$,
   $d$Senhor, tem coisa que ainda dói. Me ajuda a perdoar no meu tempo, sem fingir que não aconteceu, e a encontrar paz.$d$),
  ($d$O básico é suficiente$d$,
   $d$Miqueias resume o que o Senhor espera: agir com justiça, amar a misericórdia e andar humildemente com Deus. Uma lista curta, sem rituais complicados. Para quem se sente sempre devendo algo, é um lembrete de que o essencial cabe numa frase.$d$,
   'MIC.6.8',
   $d$Das três coisas, qual está mais difícil de praticar nesta fase?$d$,
   $d$Escolha uma das três e faça uma ação concreta hoje.$d$,
   $d$Pai, me ajuda a viver o essencial: agir com justiça, amar a misericórdia e andar com humildade contigo.$d$),
  ($d$Fé que anda no escuro$d$,
   $d$Hebreus descreve a fé como a certeza do que se espera e a convicção de coisas que não se veem. Quem confia nem sempre vê o resultado antes de caminhar. Uma leitura possível é que dúvida e fé convivem: o texto fala de seguir, não de nunca hesitar.$d$,
   'HEB.11.1',
   $d$O que você espera e ainda não vê?$d$,
   $d$Escreva uma coisa que você espera e entregue em oração, com as suas palavras.$d$,
   $d$Senhor, ajuda a minha fé quando ela vacila. Me dá coragem para seguir mesmo sem ver tudo.$d$),
  ($d$Força no que parece fraqueza$d$,
   $d$Paulo conta que ouviu que a graça era suficiente para ele e que o poder se aperfeiçoa na fraqueza. Admitir limites, aqui, não é fracasso: é o ponto onde a ajuda entra. Uma leitura possível é que você não precisa parecer inabalável para ser sustentado.$d$,
   '2CO.12.9',
   $d$Que limite seu você tem escondido porque acha que deveria dar conta?$d$,
   $d$Admita hoje um limite seu, a alguém ou a si mesmo, sem se justificar.$d$,
   $d$Pai, tenho limites e muitas vezes os escondo. Obrigado por me sustentar mesmo assim. Me ajuda a aceitar ajuda.$d$),
  ($d$Perto de quem está quebrado$d$,
   $d$O salmo diz que o Senhor está perto dos que têm o coração quebrantado e salva os de espírito abatido. Se hoje está pesado, o texto fala de proximidade, não de pressa para melhorar. Se o peso é grande ou dura há muito tempo, conversar com alguém de confiança, como um amigo, um líder ou um profissional, também é cuidado.$d$,
   'PSA.34.18',
   $d$Quem poderia saber de verdade como você está hoje?$d$,
   $d$Diga a alguém de confiança como você realmente está, em uma frase.$d$,
   $d$Senhor, hoje o coração está pesado. Fica perto de mim e me ajuda a não carregar isso sozinho.$d$),
  ($d$Para onde vai o pensamento$d$,
   $d$Paulo sugere ocupar a mente com o que é verdadeiro, nobre, correto, puro, amável e digno de louvor. É uma orientação de foco, não uma ordem para ignorar problemas. O pensamento tende a ir para onde a gente o leva com mais frequência.$d$,
   'PHP.4.8',
   $d$No que a sua cabeça mais gastou energia hoje?$d$,
   $d$Anote três coisas boas e verdadeiras do seu dia.$d$,
   $d$Pai, me ajuda a direcionar meus pensamentos para o que é bom e verdadeiro, sem negar o que é difícil.$d$),
  ($d$Contar os dias$d$,
   $d$O salmista pede que lhe ensinem a contar os dias para que o coração alcance sabedoria. Dias são limitados, e contá-los é uma forma de prestar atenção, não de viver com ansiedade. Quando a gente repara no tempo, tende a escolher melhor o que fazer com ele.$d$,
   'PSA.90.12',
   $d$Que coisa importante você tem deixado para quando sobrar tempo?$d$,
   $d$Decida o que vale a pena para os próximos 30 minutos livres do seu dia e proteja esse tempo.$d$,
   $d$Senhor, ensina-me a valorizar os meus dias, sem pressa e sem desperdício. Me ajuda a escolher bem.$d$),
  ($d$Pedir, buscar, bater$d$,
   $d$Jesus convida a pedir, a buscar e a bater, e fala em receber, encontrar e ter a porta aberta. São verbos de continuidade: o texto fala de quem não desiste de procurar. Pedir faz parte da relação, e não precisa de palavras bonitas.$d$,
   'MAT.7.7-8',
   $d$O que você tem guardado e ainda não disse em oração?$d$,
   $d$Peça hoje, com palavras simples, algo que você tem guardado.$d$,
   $d$Pai, tenho coisas para te pedir e nem sei como dizer. Ouve-me do jeito que eu consigo falar.$d$),
  ($d$Nada separa$d$,
   $d$Paulo diz estar convencido de que nada, nem a morte, nem a vida, nem o presente, nem o futuro, nem qualquer coisa criada, pode separar do amor de Deus em Cristo Jesus. Para quem tem dias em que se sente distante, o texto fala de uma relação que não depende de desempenho.$d$,
   'ROM.8.38-39',
   $d$Quando você se sentiu longe e como foi voltar?$d$,
   $d$Escreva uma frase para você mesmo lembrar nos dias em que sentir distância.$d$,
   $d$Senhor, nos dias em que me sinto longe, me lembra de que o teu amor não depende do meu desempenho.$d$),
  ($d$Amar na prática$d$,
   $d$Jesus dá um mandamento novo: amar uns aos outros como ele amou. O amor, aqui, é algo que se vê: aparece em atitudes, não só em sentimentos. Amar bem começa com gestos pequenos, para quem está por perto, no cotidiano.$d$,
   'JHN.13.34-35',
   $d$Quem da sua casa ou do seu trabalho precisa de um gesto concreto de cuidado hoje?$d$,
   $d$Faça algo concreto por alguém hoje: preparar algo, ajudar, escutar.$d$,
   $d$Pai, quero amar com atitudes, não só com palavras. Mostra-me quem precisa de mim hoje.$d$),
  ($d$Trabalho como oferta$d$,
   $d$Paulo diz para fazer o trabalho de todo o coração, como para o Senhor e não para as pessoas. Isso dá valor às tarefas comuns: lavar, escrever, atender, organizar. Fazer com atenção é uma forma de dar sentido ao que parece rotina.$d$,
   'COL.3.23',
   $d$Que tarefa de rotina você costuma fazer no automático?$d$,
   $d$Faça uma tarefa de rotina hoje com atenção total, sem outras coisas ao mesmo tempo.$d$,
   $d$Senhor, que as tarefas simples do meu dia também sejam um jeito de te honrar. Me ajuda a fazê-las com atenção.$d$),
  ($d$Uma bênção para hoje$d$,
   $d$Esta é uma bênção antiga: que o Senhor abençoe e guarde, faça resplandecer o seu rosto e conceda graça, olhe com favor e dê paz. Pode ser lida como um desejo bom para você e também como algo a oferecer a quem está perto. Termina com a palavra paz.$d$,
   'NUM.6.24-26',
   $d$Quem hoje se beneficiaria de ouvir uma palavra gentil sua?$d$,
   $d$Envie uma mensagem de carinho ou de bênção para alguém.$d$,
   $d$Senhor, abençoa e guarda quem eu amo, e a mim também. Que a tua paz esteja neste dia.$d$)
) as v(title, body, passage_reference, application_text, challenge_text, prayer_text)
where not exists (select 1 from public.content c where c.title = v.title);

-- Se este lote já tinha sido inserido como rascunho (published_at nulo), publica agora.
update public.content
set published_at = now()
where published_at is null
  and youversion_version_id = 129;

-- Para despublicar um devocional, se um dia for preciso:
--   update public.content set published_at = null where title = 'Permanecer';
